create table collection_order (order_status integer, id bigserial not null, moment timestamp(6) with time zone, user_id bigint, description varchar(255), payment bytea, primary key (id));
create table tb_address (cep integer not null, numero_casa integer not null, id bigserial not null, cidade varchar(255), estado_federativo varchar(255), nome_bairro varchar(255), nome_rua varchar(255), primary key (id));
create table tb_payment (collection_order_id bigint not null, moment timestamp(6) with time zone, primary key (collection_order_id));
create table users (address_id bigint, id bigserial not null, email varchar(255), name varchar(255), password varchar(255), phone varchar(255), primary key (id));
alter table if exists collection_order add constraint FKne0vbir0kfpm3w1o4m3tg377t foreign key (user_id) references users;
alter table if exists tb_payment add constraint FK9yh0ob84lyyu5d73nd4igkcfk foreign key (collection_order_id) references collection_order;
alter table if exists users add constraint FKjpcjmnrf9etdqro2ej4c26mti foreign key (address_id) references tb_address;
create table collection_order (order_status integer, id bigserial not null, moment timestamp(6) with time zone, user_id bigint, description varchar(255), payment bytea, primary key (id));
create table tb_address (cep integer not null, numero_casa integer not null, id bigserial not null, cidade varchar(255), estado_federativo varchar(255), nome_bairro varchar(255), nome_rua varchar(255), primary key (id));
create table tb_payment (collection_order_id bigint not null, moment timestamp(6) with time zone, primary key (collection_order_id));
create table users (address_id bigint, id bigserial not null, email varchar(255), name varchar(255), password varchar(255), phone varchar(255), primary key (id));
alter table if exists collection_order add constraint FKne0vbir0kfpm3w1o4m3tg377t foreign key (user_id) references users;
alter table if exists tb_payment add constraint FK9yh0ob84lyyu5d73nd4igkcfk foreign key (collection_order_id) references collection_order;
alter table if exists users add constraint FKjpcjmnrf9etdqro2ej4c26mti foreign key (address_id) references tb_address;
